version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-foodnexus
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodnexus_user
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak-foodnexus
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

  ms-gestionuser:
    build: .
    container_name: ms-gestionuser
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foodnexus_user?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8180/realms/foodnexus
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8180/realms/foodnexus/protocol/openid-connect/certs
      KEYCLOAK_ADMIN_SERVER_URL: http://keycloak:8180
      KEYCLOAK_ADMIN_REALM: foodnexus
      KEYCLOAK_ADMIN_CLIENT_ID: foodnexus-app
      KEYCLOAK_ADMIN_CLIENT_SECRET: l9ea6k7SmatXfY2FObT1c0rNkojey9JL
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
    depends_on:
      - mysql
      - keycloak

volumes:
  mysql-data: